penalty=10.0
alpha=1.0

datasets=100_dense,100_sparse,200_dense,200_sparse,500_dense,500_sparse

dataset.100_dense.file=data/instance_100_dense.csv
dataset.100_dense.count=20
dataset.100_dense.minAttr=0.5

dataset.100_sparse.file=data/instance_100_sparse.csv
dataset.100_sparse.count=20
dataset.100_sparse.minAttr=0.5

dataset.200_dense.file=data/instance_200_dense.csv
dataset.200_dense.count=30
dataset.200_dense.minAttr=0.5

dataset.200_sparse.file=data/instance_200_sparse.csv
dataset.200_sparse.count=30
dataset.200_sparse.minAttr=0.5

dataset.500_dense.file=data/instance_500_dense.csv
dataset.500_dense.count=50
dataset.500_dense.minAttr=0.5

dataset.500_sparse.file=data/instance_500_sparse.csv
dataset.500_sparse.count=50
dataset.500_sparse.minAttr=0.5

taguchi.replications=5

# liczba niezaleznych przebiegow do wynikow w raporcie (mean/std/min/max)
stats.runs=10

# PSO variants
pso.pBus=0.3
pso.penaltyMin=2.0
pso.penaltyMax=10.0
